### ISSUE TITLE
Include affected services in release message

### ISSUE THREAD

**Issue by iainelder** [z0ph/MAMIP#10]
For convenience in my environments I sometimes use the AWS-managed policies directly instead of my own.

So it's also convenient to subscribe to this repo to keep track of changes AWS makes that could affect my environment's security.

It would be even more convenient if the release message that I get in my email included the affected services so that I don't have to click through to Github to read every diff.

A list of changed files would be good enough, as they are normally named after the service.

**Comment by iainelder** [comment]
For example, for the most recent release, not just

> Update detected on refs/tags/2021-02-18-08-01

https://github.com/z0ph/aws_managed_policies/releases/tag/2021-02-18-08-01

but also

> Changes:
>
> * policies/AWSProtonDeveloperAccess
> * policies/AWSProtonFullAccess
> * policies/AWSProtonReadOnlyAccess
> * policies/AWSStorageGatewayServiceRolePolicy

(Derived from https://github.com/z0ph/aws_managed_policies/commit/7ea4bab55d663182fe827943c5a2462f069d5a88)

**Comment by z0ph** [comment]
Thanks, @iainelder,

I will work on this idea, will tell you of my findings. Thanks for your proposal.

**Comment by z0ph** [comment]
The first try was a fail. Still trying to find something working.

**Comment by z0ph** [comment]
Should be ok with this new approach see #24 for more details.

![image](https://user-images.githubusercontent.com/20846187/113665692-39046f80-96ae-11eb-8a83-e2881afa7b57.png)
