### ISSUE TITLE
AWSECRPullThroughCacheServiceRolePolicy empty

### ISSUE THREAD

**Issue by iann0036** [z0ph/MAMIP#32]
policies/AWSECRPullThroughCacheServiceRolePolicy looks empty? :)

**Comment by z0ph** [comment]
Hey @iann0036 👋🏼 

This was deprecated by https://github.com/z0ph/MAMIP/blob/master/policies/AWSECRPullThroughCache_ServiceRolePolicy

![CleanShot 2021-11-27 at 13 28 39](https://user-images.githubusercontent.com/20846187/143681317-a4e5a298-d441-4935-a815-5efb60765eda.png)

Removed by: a5c101bd259f2a654a6fd1d1a3868b9b6d8e0632
