### ISSUE TITLE
Hall of fails - CloudWatchFullAccess

### ISSUE THREAD

**Issue by danieljamesscott** [z0ph/MAMIP#38]
I've always thought that `CloudWatchFullAccess` was excessively broad. It contains `Allow` on `sns:*`. There's probably a good reason for this, to allow the console to create alarm subscriptions, but I think it could have a better name, or even a separate policy for 'only' full CW access.

Is this something worth adding to the hall of fails?

**Comment by z0ph** [comment]
I agree with you, this is misleading and could be used by an attacker to do wrong things to `sns` scope.

To give more context, here is the policy in question: https://github.com/z0ph/MAMIP/blob/master/policies/CloudWatchFullAccess#L11

I ask others throughs to my colleagues: @0xdabbad00 / @aidansteele / @iann0036 :)

**Comment by iann0036** [comment]
I've mostly given up on Managed Policies. There's [a whole bunch](https://aws.permissions.cloud/managedpolicies) with various issues, so you may just want to make a more generic Hall of Fails entry here.

**Comment by z0ph** [comment]
Really nice Iann, thanks for your feedback, I like the privilege escalation tag with the culprit action. Are you using CloudSplaining under the hood?

**Comment by iann0036** [comment]
Grabbed the list of actions from CloudSplaining / HackingThe.Cloud
