### ISSUE TITLE
Licence used for the project

### ISSUE THREAD

**Issue by claer** [z0ph/MAMIP#46]
Hi,

Is it possible to describe the license attached to the project?

Thanks!

**Comment by z0ph** [comment]
Hi, 

Described in #47.

👋🏼

**Comment by claer** [comment]
Thanks :)

**Comment by z0ph** [comment]
> Thanks :)

Do you have any specific use cases in mind?

**Comment by claer** [comment]
Yes, I'd like to deploy the tf code on one of my account to alert on changes on used managed policy. As it had no licence specified, it is the same as no licence allowed for users. Our company policy don't allow to use such unlicenced code.
